-- Inserindo 50 empresas com seus dados e 5 vagas de tecnologia cada
INSERT INTO company (name, cnpj, phone, email, password, status) VALUES
    ('Amazon Web Services (AWS) Brasil', '00000000000000', '11999999999', 'aws.brasil@amazon.com', 'aws123', 'active'),
    ('Google Brasil', '00000000000001', '11999999998', 'google.brasil@google.com', 'google123', 'active'),
    ('Microsoft Brasil', '00000000000002', '11999999997', 'microsoft.brasil@microsoft.com', 'microsoft123', 'active'),
    ('Meta Platforms Brasil', '00000000000003', '11999999996', 'meta.brasil@meta.com', 'meta123', 'active'),
    ('IBM Brasil', '00000000000004', '11999999995', 'ibm.brasil@ibm.com', 'ibm123', 'active'),
    ('Apple Brasil', '00000000000005', '11999999994', 'apple.brasil@apple.com', 'apple123', 'active'),
    ('Oracle Brasil', '00000000000006', '11999999993', 'oracle.brasil@oracle.com', 'oracle123', 'active'),
    ('SAP Brasil', '00000000000007', '11999999992', 'sap.brasil@sap.com', 'sap123', 'active'),
    ('Accenture Brasil', '00000000000008', '11999999991', 'accenture.brasil@accenture.com', 'accenture123', 'active'),
    ('Deloitte Brasil', '00000000000009', '11999999990', 'deloitte.brasil@deloitte.com', 'deloitte123', 'active'),
    ('EY Brasil', '00000000000010', '11999999989', 'ey.brasil@ey.com', 'ey123', 'active'),
    ('PwC Brasil', '00000000000011', '11999999988', 'pwc.brasil@pwc.com', 'pwc123', 'active'),
    ('Bradesco', '00000000000012', '11999999987', 'bradesco@bradesco.com.br', 'bradesco123', 'active'),
    ('Itaú Unibanco', '00000000000013', '11999999986', 'itau.unibanco@itau.com.br', 'itau123', 'active'),
    ('Banco do Brasil', '00000000000014', '11999999985', 'bb@bb.com.br', 'bb123', 'active'),
    ('Santander Brasil', '00000000000015', '11999999984', 'santander.brasil@santander.com.br', 'santander123', 'active'),
    ('Nubank', '00000000000016', '11999999983', 'nubank@nubank.com.br', 'nubank123', 'active'),
    ('Magazine Luiza', '00000000000017', '11999999982', 'magazineluiza@magazineluiza.com.br', 'magazineluiza123', 'active'),
    ('Via Varejo', '00000000000018', '11999999981', 'viavarejo@viavarejo.com.br', 'viavarejo123', 'active'),
    ('Ambev', '00000000000019', '11999999980', 'ambev@ambev.com.br', 'ambev123', 'active'),
    ('Petrobras', '00000000000020', '11999999979', 'petrobras@petrobras.com.br', 'petrobras123', 'active'),
    ('Vale', '00000000000021', '11999999978', 'vale@vale.com.br', 'vale123', 'active'),
    ('Gerdau', '00000000000022', '11999999977', 'gerdau@gerdau.com.br', 'gerdau123', 'active'),
    ('JBS', '00000000000023', '11999999976', 'jbs@jbs.com.br', 'jbs123', 'active'),
    ('BRF', '00000000000024', '11999999975', 'brf@brf.com.br', 'brf123', 'active'),
    ('WEG', '00000000000025', '11999999974', 'weg@weg.com.br', 'weg123', 'active'),
    ('Rumo', '00000000000026', '11999999973', 'rumo@rumo.com.br', 'rumo123', 'active'),
    ('Suzano', '00000000000027', '11999999972', 'suzano@suzano.com.br', 'suzano123', 'active'),
    ('Klabin', '00000000000028', '11999999971', 'klabin@klabin.com.br', 'klabin123', 'active'),
    ('Iguatemi', '00000000000029', '11999999970', 'iguatemi@iguatemi.com.br', 'iguatemi123', 'active'),
    ('Multiplan', '00000000000030', '11999999969', 'multiplan@multiplan.com.br', 'multiplan123', 'active'),
    ('CCR', '00000000000031', '11999999968', 'ccr@ccr.com.br', 'ccr123', 'active'),
    ('EcoRodovias', '00000000000032', '11999999967', 'ecorodovias@ecorodovias.com.br', 'ecorodovias123', 'active'),
    ('Fleury', '00000000000033', '11999999966', 'fleury@fleury.com.br', 'fleury123', 'active'),
    ("Rede D'Or", '00000000000034', '11999999965', 'rededor@rededor.com.br', 'rededor123', 'active'),
    ('Hapvida', '00000000000035', '11999999964', 'hapvida@hapvida.com.br', 'hapvida123', 'active'),
    ('SulAmérica', '00000000000036', '11999999963', 'sulamerica@sulamerica.com.br', 'sulamerica123', 'active'),
    ('Amil', '00000000000037', '11999999962', 'amil@amil.com.br', 'amil123', 'active'),
    ('Algar Telecom', '00000000000038', '11999999961', 'algartelecom@algartelecom.com.br', 'algartelecom123', 'active'),
    ('Claro Brasil', '00000000000039', '11999999960', 'claro.brasil@claro.com.br', 'claro123', 'active'),
    ('Oi', '00000000000040', '11999999959', 'oi@oi.com.br', 'oi123', 'active'),
    ('TIM Brasil', '00000000000041', '11999999958', 'tim.brasil@tim.com.br', 'tim123', 'active'),
    ('Vivo', '00000000000042', '11999999957', 'vivo@vivo.com.br', 'vivo123', 'active'),
    ('Localiza', '00000000000043', '11999999956', 'localiza@localiza.com.br', 'localiza123', 'active'),
    ('Movida', '00000000000044', '11999999955', 'movida@movida.com.br', 'movida123', 'active'),
    ('Unidas', '00000000000045', '11999999954', 'unidas@unidas.com.br', 'unidas123', 'active'),
    ('GOL Linhas Aéreas', '00000000000046', '11999999953', 'gol@gol.com.br', 'gol123', 'active'),
    ('LATAM Airlines Brasil', '00000000000047', '11999999952', 'latam.brasil@latam.com', 'latam123', 'active'),
    ('Azul Linhas Aéreas', '00000000000048', '11999999951', 'azul@voeazul.com.br', 'azul123', 'active'),
    ('Embraer', '00000000000049', '11999999950', 'embraer@embraer.com', 'embraer123', 'active'),
    ('Cielo', '00000000000050', '11999999949', 'cielo@cielo.com.br', 'cielo123', 'active');


INSERT INTO vacancy (title, description, arrangement, type, location, salary, companyID, status) VALUES
    ('Desenvolvedor Front-End', 'Desenvolver interfaces de usuário utilizando tecnologias como React, Angular ou Vue.js. Experiência com HTML, CSS e JavaScript.', 'Remote', 'CLT', 'São Paulo', '10000', 1, 'active'),
    ('Desenvolvedor Back-End', 'Desenvolver APIs e serviços utilizando Node.js, Python (Django ou Flask) ou Java. Experiência com bancos de dados relacionais (SQL).', 'Hybrid', 'CLT', 'Rio de Janeiro', '12000', 1, 'active'),
    ('Engenheiro de DevOps', 'Gerenciar a infraestrutura e os sistemas de uma plataforma de software utilizando ferramentas como Docker, Kubernetes, Terraform e Ansible.', 'Onsite', 'CLT', 'Belo Horizonte', '15000', 1, 'active'),
    ('Cientista de Dados', 'Coletar, analisar e interpretar dados utilizando linguagem Python (Pandas, Scikit-learn) para gerar insights e melhorar decisões de negócio.', 'Remote', 'CLT', 'Curitiba', '13000', 1, 'active'),
    ('Analista de Segurança da Informação', 'Assegurar a segurança dos sistemas e dados da empresa, realizando testes de penetração, análise de vulnerabilidades e gestão de riscos.', 'Hybrid', 'CLT', 'Porto Alegre', '11000', 1, 'active'),

    ('Engenheiro de Software', 'Desenvolver, testar e implantar software de alta qualidade utilizando tecnologias como Java, Python ou C#. Experiência com metodologias ágeis.', 'Hybrid', 'CLT', 'São Paulo', '14000', 2, 'active'),
    ('Desenvolvedor Android', 'Desenvolver aplicativos mobile para Android utilizando Java ou Kotlin. Experiência com UI/UX, APIs e testes de software.', 'Onsite', 'CLT', 'Rio de Janeiro', '13000', 2, 'active'),
    ('Desenvolvedor iOS', 'Desenvolver aplicativos mobile para iOS utilizando Swift. Experiência com UI/UX, APIs e testes de software.', 'Remote', 'CLT', 'Belo Horizonte', '12000', 2, 'active'),
    ('Arquiteto de Soluções', 'Desenvolver e implementar soluções de tecnologia complexas, incluindo arquitetura de sistemas, design de soluções e integração de diferentes plataformas.', 'Onsite', 'CLT', 'Curitiba', '16000', 2, 'active'),
    ('Gerente de Projetos de Software', 'Gerenciar projetos de desenvolvimento de software, garantindo o cumprimento de prazos, custos e qualidade.', 'Hybrid', 'CLT', 'Porto Alegre', '15000', 2, 'active'),

    ('Desenvolvedor .NET', 'Desenvolver soluções web e mobile utilizando tecnologias .NET, C# e ASP.NET. Experiência com bancos de dados relacionais (SQL).', 'Hybrid', 'CLT', 'São Paulo', '12000', 3, 'active'),
    ('Arquiteto de Nuvem', 'Desenhar e implementar soluções de arquitetura de nuvem utilizando tecnologias como Azure, AWS ou GCP. Experiência com infraestrutura e serviços de nuvem.', 'Remote', 'CLT', 'Rio de Janeiro', '15000', 3, 'active'),
    ('Analista de Big Data', 'Coletar, analisar e interpretar grandes volumes de dados utilizando ferramentas como Hadoop, Spark e Hive para gerar insights e melhorar decisões de negócio.', 'Onsite', 'CLT', 'Belo Horizonte', '14000', 3, 'active'),
    ('Especialista em Segurança Cibernética', 'Proteger sistemas e dados contra ameaças cibernéticas, realizando análise de riscos, detecção de intrusões e resposta a incidentes.', 'Hybrid', 'CLT', 'Curitiba', '13000', 3, 'active'),
    ('Consultor de Soluções de Negócios', 'Entender as necessidades dos clientes e apresentar soluções de tecnologia que atendam suas expectativas, realizando consultoria, implementação e suporte.', 'Onsite', 'CLT', 'Porto Alegre', '12000', 3, 'active'),

    ('Engenheiro de Machine Learning', 'Desenvolver e implementar modelos de machine learning para resolver problemas complexos, utilizando linguagem Python (TensorFlow, PyTorch).', 'Remote', 'CLT', 'São Paulo', '15000', 4, 'active'),
    ('Desenvolvedor de Interfaces Conversacionais', 'Desenvolver chatbots e assistentes virtuais utilizando tecnologias como Dialogflow, Watson Assistant ou Amazon Lex.', 'Hybrid', 'CLT', 'Rio de Janeiro', '13000', 4, 'active'),
    ('Especialista em Blockchain', 'Desenvolver soluções utilizando tecnologias de blockchain para aplicações como criptomoedas, contratos inteligentes e gerenciamento de dados.', 'Onsite', 'CLT', 'Belo Horizonte', '14000', 4, 'active'),
    ('Desenvolvedor Full-Stack', 'Desenvolver aplicações web completas utilizando tecnologias como React, Node.js, MongoDB e bancos de dados relacionais.', 'Hybrid', 'CLT', 'Curitiba', '13000', 4, 'active'),
    ('Analista de Dados de Negócios', 'Coletar, analisar e interpretar dados para gerar insights e tomar decisões estratégicas, utilizando ferramentas de BI e análise de dados.', 'Onsite', 'CLT', 'Porto Alegre', '12000', 4, 'active'),

    ('Desenvolvedor Java', 'Desenvolver aplicações Java utilizando Spring Framework, Hibernate e outras tecnologias Java. Experiência com testes unitários.', 'Hybrid', 'CLT', 'São Paulo', '13000', 5, 'active'),
    ('Arquiteto de Microserviços', 'Desenvolver e implementar sistemas baseados em microserviços, utilizando tecnologias como Docker, Kubernetes e APIs RESTful.', 'Remote', 'CLT', 'Rio de Janeiro', '16000', 5, 'active'),
    ('Analista de Infraestrutura de TI', 'Gerenciar a infraestrutura de TI, incluindo servidores, redes e sistemas operacionais, garantindo a disponibilidade e segurança.', 'Onsite', 'CLT', 'Belo Horizonte', '14000', 5, 'active'),
    ('Desenvolvedor de Software Embarcado', 'Desenvolver software para sistemas embarcados, utilizando linguagem C e conhecimentos em hardware.', 'Hybrid', 'CLT', 'Curitiba', '12000', 5, 'active'),
    ('Consultor de Integração de Sistemas', 'Realizar integração de sistemas e plataformas utilizando tecnologias como middleware, APIs e ETL.', 'Onsite', 'CLT', 'Porto Alegre', '11000', 5, 'active'),

    ('Desenvolvedor Python', 'Desenvolver aplicações utilizando linguagem Python (Django, Flask) e bancos de dados relacionais (SQL). Experiência com testes unitários.', 'Remote', 'CLT', 'São Paulo', '12000', 6, 'active'),
    ('Engenheiro de Teste de Software', 'Desenvolver e executar testes de software utilizando diferentes metodologias e ferramentas. Experiência em testes funcionais, de desempenho e de segurança.', 'Onsite', 'CLT', 'Rio de Janeiro', '11000', 6, 'active'),
    ('Analista de Negócios de TI', 'Analisar as necessidades de negócio e traduzi-las em soluções de tecnologia, utilizando conhecimentos de processos de negócio e de sistemas.', 'Hybrid', 'CLT', 'Belo Horizonte', '13000', 6, 'active'),
    ('Desenvolvedor de Jogos', 'Desenvolver jogos utilizando linguagens como C#, C++ e Unity. Experiência em design de jogos, programação e testes.', 'Hybrid', 'CLT', 'Curitiba', '12000', 6, 'active'),
    ('Consultor de Segurança da Informação', 'Prestar consultoria em segurança da informação, realizando análise de riscos, auditorias e implementação de medidas de segurança.', 'Onsite', 'CLT', 'Porto Alegre', '14000', 6, 'active'),

    ('Arquiteto de Software', 'Definir e implementar a arquitetura de software de sistemas complexos, utilizando diferentes tecnologias e frameworks. Experiência em design patterns e princípios de arquitetura.', 'Hybrid', 'CLT', 'São Paulo', '16000', 7, 'active'),
    ('Desenvolvedor PHP', 'Desenvolver aplicações web utilizando linguagem PHP (Laravel, Symfony) e bancos de dados relacionais (SQL). Experiência com testes unitários.', 'Remote', 'CLT', 'Rio de Janeiro', '13000', 7, 'active'),
    ('Analista de Sistemas', 'Analisar, projetar, desenvolver e implementar sistemas de informação, utilizando diferentes tecnologias e ferramentas.', 'Onsite', 'CLT', 'Belo Horizonte', '12000', 7, 'active'),
    ('Desenvolvedor Web', 'Desenvolver aplicações web utilizando HTML, CSS, JavaScript, jQuery e outros frameworks. Experiência com APIs e testes de software.', 'Hybrid', 'CLT', 'Curitiba', '11000', 7, 'active'),
    ('Consultor de Implementação de Software', 'Realizar a implementação de software para clientes, garantindo a configuração, treinamento e suporte.', 'Onsite', 'CLT', 'Porto Alegre', '15000', 7, 'active'),

    ('Desenvolvedor JavaScript', 'Desenvolver aplicações web utilizando JavaScript, React, Angular, Vue.js, Node.js, e outras tecnologias relacionadas.', 'Remote', 'CLT', 'São Paulo', '14000', 8, 'active'),
    ('Engenheiro de Dados', 'Projetar, desenvolver e implementar sistemas de gerenciamento de dados, utilizando tecnologias como Hadoop, Spark, Hive e bancos de dados NoSQL.', 'Onsite', 'CLT', 'Rio de Janeiro', '15000', 8, 'active'),
    ('Analista de BI', 'Desenvolver e implementar soluções de business intelligence, utilizando ferramentas de análise de dados, relatórios e dashboards.', 'Hybrid', 'CLT', 'Belo Horizonte', '13000', 8, 'active'),
    ('Desenvolvedor de Aplicações Mobile', 'Desenvolver aplicativos mobile para Android e iOS utilizando diferentes frameworks e tecnologias.', 'Hybrid', 'CLT', 'Curitiba', '12000', 8, 'active'),
    ('Consultor de Soluções de Integração', 'Prestar consultoria em soluções de integração de sistemas, utilizando diferentes tecnologias e ferramentas de integração.', 'Onsite', 'CLT', 'Porto Alegre', '11000', 8, 'active'),

    ('Desenvolvedor Ruby on Rails', 'Desenvolver aplicações web utilizando Ruby on Rails e bancos de dados relacionais (SQL). Experiência com testes unitários.', 'Hybrid', 'CLT', 'São Paulo', '13000', 9, 'active'),
    ('Arquiteto de Integração', 'Desenvolver e implementar soluções de integração de sistemas, utilizando tecnologias como middleware, APIs e ETL.', 'Remote', 'CLT', 'Rio de Janeiro', '15000', 9, 'active'),
    ('Analista de Testes de Performance', 'Desenvolver e executar testes de performance de software utilizando diferentes ferramentas e técnicas.', 'Onsite', 'CLT', 'Belo Horizonte', '12000', 9, 'active'),
    ('Desenvolvedor de Sistemas Embarcados', 'Desenvolver software para sistemas embarcados utilizando linguagem C, C++ e conhecimentos em hardware.', 'Hybrid', 'CLT', 'Curitiba', '14000', 9, 'active'),
    ('Consultor de UX/UI', 'Prestar consultoria em experiência do usuário e interface do usuário, realizando análise, design e implementação de interfaces.', 'Onsite', 'CLT', 'Porto Alegre', '13000', 9, 'active'),

    ('Engenheiro de Software Sênior', 'Desenvolver, testar e implantar software de alta complexidade utilizando tecnologias como Java, Python, C# e outras. Experiência em liderança técnica.', 'Hybrid', 'CLT', 'São Paulo', '18000', 10, 'active'),
    ('Desenvolvedor de Aplicativos Web', 'Desenvolver aplicações web utilizando HTML, CSS, JavaScript, jQuery e outros frameworks. Experiência com APIs e testes de software.', 'Remote', 'CLT', 'Rio de Janeiro', '14000', 10, 'active'),
    ('Analista de Suporte de TI', 'Prestar suporte técnico aos usuários, resolvendo problemas relacionados a hardware, software e redes.', 'Onsite', 'CLT', 'Belo Horizonte', '11000', 10, 'active'),
    ('Desenvolvedor de Banco de Dados', 'Projetar, desenvolver e gerenciar bancos de dados relacionais (SQL) e NoSQL.', 'Hybrid', 'CLT', 'Curitiba', '12000', 10, 'active'),
    ('Consultor de Cloud Computing', 'Prestar consultoria em soluções de cloud computing, incluindo arquitetura, implementação e gestão de plataformas de nuvem.', 'Onsite', 'CLT', 'Porto Alegre', '13000', 10, 'active'),

    ('Desenvolvedor de Aplicativos Mobile', 'Desenvolver aplicativos móveis para Android e iOS utilizando diferentes frameworks e tecnologias.', 'Remote', 'CLT', 'São Paulo', '13000', 11, 'active'),
    ('Engenheiro de Automação de Testes', 'Desenvolver e implementar testes automatizados para software, utilizando ferramentas e frameworks de automação.', 'Onsite', 'CLT', 'Rio de Janeiro', '12000', 11, 'active'),
    ('Analista de Sistemas', 'Analisar, projetar, desenvolver e implementar sistemas de informação, utilizando diferentes tecnologias e ferramentas.', 'Hybrid', 'CLT', 'Belo Horizonte', '11000', 11, 'active'),
    ('Desenvolvedor de API', 'Desenvolver APIs RESTful utilizando diferentes tecnologias e frameworks.', 'Hybrid', 'CLT', 'Curitiba', '13000', 11, 'active'),
    ('Consultor de BI', 'Prestar consultoria em soluções de business intelligence, incluindo análise de dados, relatórios e dashboards.', 'Onsite', 'CLT', 'Porto Alegre', '14000', 11, 'active'),

    ('Arquiteto de Soluções de Software', 'Desenvolver e implementar soluções de tecnologia complexas, incluindo arquitetura de sistemas, design de soluções e integração de diferentes plataformas.', 'Hybrid', 'CLT', 'São Paulo', '16000', 12, 'active'),
    ('Desenvolvedor C++', 'Desenvolver aplicações utilizando linguagem C++ e bancos de dados relacionais (SQL). Experiência com testes unitários.', 'Remote', 'CLT', 'Rio de Janeiro', '14000', 12, 'active'),
    ('Analista de Qualidade de Software', 'Garantir a qualidade do software através de testes manuais e automatizados.', 'Onsite', 'CLT', 'Belo Horizonte', '12000', 12, 'active'),
    ('Desenvolvedor de Sistemas Embarcados', 'Desenvolver software para sistemas embarcados utilizando linguagem C, C++ e conhecimentos em hardware.', 'Hybrid', 'CLT', 'Curitiba', '13000', 12, 'active'),
    ('Consultor de ERP', 'Prestar consultoria em soluções de ERP, incluindo implementação, treinamento e suporte.', 'Onsite', 'CLT', 'Porto Alegre', '15000', 12, 'active'),

    ('Desenvolvedor Front-End', 'Desenvolver interfaces de usuário utilizando tecnologias como React, Angular ou Vue.js. Experiência com HTML, CSS e JavaScript.', 'Remote', 'CLT', 'São Paulo', '14000', 13, 'active'),
    ('Desenvolvedor Back-End', 'Desenvolver APIs e serviços utilizando Node.js, Python (Django ou Flask) ou Java. Experiência com bancos de dados relacionais (SQL).', 'Hybrid', 'CLT', 'Rio de Janeiro', '15000', 13, 'active'),
    ('Engenheiro de DevOps', 'Gerenciar a infraestrutura e os sistemas de uma plataforma de software utilizando ferramentas como Docker, Kubernetes, Terraform e Ansible.', 'Onsite', 'CLT', 'Belo Horizonte', '17000', 13, 'active'),
    ('Cientista de Dados', 'Coletar, analisar e interpretar dados utilizando linguagem Python (Pandas, Scikit-learn) para gerar insights e melhorar decisões de negócio.', 'Remote', 'CLT', 'Curitiba', '16000', 13, 'active'),
    ('Analista de Segurança da Informação', 'Assegurar a segurança dos sistemas e dados da empresa, realizando testes de penetração, análise de vulnerabilidades e gestão de riscos.', 'Hybrid', 'CLT', 'Porto Alegre', '15000', 13, 'active'),

    ('Desenvolvedor de Software', 'Desenvolver, testar e implantar software de alta qualidade utilizando tecnologias como Java, Python ou C#. Experiência com metodologias ágeis.', 'Hybrid', 'CLT', 'São Paulo', '15000', 14, 'active'),
    ('Desenvolvedor Android', 'Desenvolver aplicativos mobile para Android utilizando Java ou Kotlin. Experiência com UI/UX, APIs e testes de software.', 'Onsite', 'CLT', 'Rio de Janeiro', '14000', 14, 'active'),
    ('Desenvolvedor iOS', 'Desenvolver aplicativos mobile para iOS utilizando Swift. Experiência com UI/UX, APIs e testes de software.', 'Remote', 'CLT', 'Belo Horizonte', '13000', 14, 'active'),
    ('Arquiteto de Soluções', 'Desenvolver e implementar soluções de tecnologia complexas, incluindo arquitetura de sistemas, design de soluções e integração de diferentes plataformas.', 'Onsite', 'CLT', 'Curitiba', '16000', 14, 'active'),
    ('Gerente de Projetos de Software', 'Gerenciar projetos de desenvolvimento de software, garantindo o cumprimento de prazos, custos e qualidade.', 'Hybrid', 'CLT', 'Porto Alegre', '15000', 14, 'active'),

    ('Desenvolvedor .NET', 'Desenvolver soluções web e mobile utilizando tecnologias .NET, C# e ASP.NET. Experiência com bancos de dados relacionais (SQL).', 'Hybrid', 'CLT', 'São Paulo', '14000', 15, 'active'),
    ('Arquiteto de Nuvem', 'Desenhar e implementar soluções de arquitetura de nuvem utilizando tecnologias como Azure, AWS ou GCP. Experiência com infraestrutura e serviços de nuvem.', 'Remote', 'CLT', 'Rio de Janeiro', '17000', 15, 'active'),
    ('Analista de Big Data', 'Coletar, analisar e interpretar grandes volumes de dados utilizando ferramentas como Hadoop, Spark e Hive para gerar insights e melhorar decisões de negócio.', 'Onsite', 'CLT', 'Belo Horizonte', '15000', 15, 'active'),
    ('Especialista em Segurança Cibernética', 'Proteger sistemas e dados contra ameaças cibernéticas, realizando análise de riscos, detecção de intrusões e resposta a incidentes.', 'Hybrid', 'CLT', 'Curitiba', '14000', 15, 'active'),
    ('Consultor de Soluções de Negócios', 'Entender as necessidades dos clientes e apresentar soluções de tecnologia que atendam suas expectativas, realizando consultoria, implementação e suporte.', 'Onsite', 'CLT', 'Porto Alegre', '13000', 15, 'active'),

    ('Engenheiro de Machine Learning', 'Desenvolver e implementar modelos de machine learning para resolver problemas complexos, utilizando linguagem Python (TensorFlow, PyTorch).', 'Remote', 'CLT', 'São Paulo', '17000', 16, 'active'),
    ('Desenvolvedor de Interfaces Conversacionais', 'Desenvolver chatbots e assistentes virtuais utilizando tecnologias como Dialogflow, Watson Assistant ou Amazon Lex.', 'Hybrid', 'CLT', 'Rio de Janeiro', '15000', 16, 'active'),
    ('Especialista em Blockchain', 'Desenvolver soluções utilizando tecnologias de blockchain para aplicações como criptomoedas, contratos inteligentes e gerenciamento de dados.', 'Onsite', 'CLT', 'Belo Horizonte', '16000', 16, 'active'),
    ('Desenvolvedor Full-Stack', 'Desenvolver aplicações web completas utilizando tecnologias como React, Node.js, MongoDB e bancos de dados relacionais.', 'Hybrid', 'CLT', 'Curitiba', '14000', 16, 'active'),
    ('Analista de Dados de Negócios', 'Coletar, analisar e interpretar dados para gerar insights e tomar decisões estratégicas, utilizando ferramentas de BI e análise de dados.', 'Onsite', 'CLT', 'Porto Alegre', '13000', 16, 'active'),

    ('Desenvolvedor Java', 'Desenvolver aplicações Java utilizando Spring Framework, Hibernate e outras tecnologias Java. Experiência com testes unitários.', 'Hybrid', 'CLT', 'São Paulo', '15000', 17, 'active'),
    ('Arquiteto de Microserviços', 'Desenvolver e implementar sistemas baseados em microserviços, utilizando tecnologias como Docker, Kubernetes e APIs RESTful.', 'Remote', 'CLT', 'Rio de Janeiro', '18000', 17, 'active'),
    ('Analista de Infraestrutura de TI', 'Gerenciar a infraestrutura de TI, incluindo servidores, redes e sistemas operacionais, garantindo a disponibilidade e segurança.', 'Onsite', 'CLT', 'Belo Horizonte', '16000', 17, 'active'),
    ('Desenvolvedor de Software Embarcado', 'Desenvolver software para sistemas embarcados, utilizando linguagem C e conhecimentos em hardware.', 'Hybrid', 'CLT', 'Curitiba', '14000', 17, 'active'),
    ('Consultor de Integração de Sistemas', 'Realizar integração de sistemas e plataformas utilizando tecnologias como middleware, APIs e ETL.', 'Onsite', 'CLT', 'Porto Alegre', '13000', 17, 'active'),

    ('Desenvolvedor Python', 'Desenvolver aplicações utilizando linguagem Python (Django, Flask) e bancos de dados relacionais (SQL). Experiência com testes unitários.', 'Remote', 'CLT', 'São Paulo', '14000', 18, 'active'),
    ('Engenheiro de Teste de Software', 'Desenvolver e executar testes de software utilizando diferentes metodologias e ferramentas. Experiência em testes funcionais, de desempenho e de segurança.', 'Onsite', 'CLT', 'Rio de Janeiro', '13000', 18, 'active'),
    ('Analista de Negócios de TI', 'Analisar as necessidades de negócio e traduzi-las em soluções de tecnologia, utilizando conhecimentos de processos de negócio e de sistemas.', 'Hybrid', 'CLT', 'Belo Horizonte', '15000', 18, 'active'),
    ('Desenvolvedor de Jogos', 'Desenvolver jogos utilizando linguagens como C#, C++ e Unity. Experiência em design de jogos, programação e testes.', 'Hybrid', 'CLT', 'Curitiba', '14000', 18, 'active') ;